login/urls.py
from django.urls import path
from . import views


app_name = 'login'
urlpatterns = [
    path('', views.login_request, name='login'),
    path('logout', views.logout_request, name='logout')
]

registration/urls.py
from django.urls import path
from .views import RegisterUser


app_name = 'registration'
urlpatterns = [
    path('', RegisterUser.as_view(), name='registration'),
]

sensorslist/urls.py
from django.urls import path
from . import views



app_name = 'sensorslist'
urlpatterns = [
    path('', views.sensorshow, name='sensorslist'),
    path('delete_data/', views.delete_data, name='delete_data'),
    path('save_data/', views.save_data, name='save_data'),
    path('load_data/', views.load_data, name='load_data'),
    path('plot_data/', views.plot_data, name='plot_data'),
]
# <!--<div id="container" style="width: 75%;">-->
#         //    <!--<canvas id="population-chart" data-url="{% url 'core:population-chart' %}"></canvas>-->
#         //<!--</div>-->

sensorsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from login.views import *
#import django.contrib.auth.urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls'), name='login'),
    path('registration/', include('registration.urls'), name='registration'),
    path('sensorslist/', include('sensorslist.urls'), name='sensorslist'),
]

login/models.py
from django.db import models

# Create your models here.

sensorslist/models.py
from django.db import models



class Sensor(models.Model):
    name = models.CharField(max_length=30)
    user = models.CharField(max_length=30)
    pub_date = models.DateTimeField('date published')
    time = list()
    signal = list()

    def __str__(self):
        return self.name

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm



def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("sensorslist:sensorslist")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="login/login.html", context={"login_form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect("{% url 'login:login' %}")

sensorslist/views.py
from .models import Sensor
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Sensor
from .devices import *



@login_required(login_url='/login')
def sensorshow(request):
    print(request)
    print(request.method == 'GET')
    sensors_list = Sensor.objects.all().order_by('-pub_date') #sort by adding date
    template = loader.get_template('sensorslist/sensors.html')
    context = {
        'sensors_list': sensors_list,
        'username': request.user.username,
    }
    return HttpResponse(template.render(context, request))


@csrf_exempt # to avoid error 403
def delete_data(request):
    req = dict(request.POST)
    for key in req.keys():
        req[key] = req[key][0]
    object_to_delete = Sensor.objects.filter(user=req['User'], name=req['Name'])
    object_to_delete.delete()
    return HttpResponse(status=200)


@csrf_exempt # to avoid error 403
def save_data(request):
    req = dict(request.POST)
    for key in req.keys():
        req[key] = req[key][0]
    object_to_save = Sensor(user=req['User'], name=req['Name'], pub_date=timezone.now())
    object_to_save.save()
    return HttpResponse(status=200)


@csrf_exempt # to avoid error 403
def load_data(request):
    req = dict(request.POST)
    for key in req.keys():
        req[key] = req[key][0]
    create_device(str(req['Name']))
    write_measurements(str(req['Name']))
    return HttpResponse(status=200)


@csrf_exempt # to avoid error 403
def plot_data(request):
    req = dict(request.POST)
    for key in req.keys():
        req[key] = req[key][0]
    
    # запрос в бд
    sensor_name = req['Name']
    device_filter = f'r.device == "{sensor_name}"'
    query = f'from(bucket: "{config.get("APP", "INFLUX_BUCKET")}") ' \
            f'|> range(start: 0, stop: now()) ' \
            f'|> filter(fn: (r) => {device_filter} and r._field == "Temperature")' \
            '|> sort(columns: ["_time"]) '
    data = get_measurements(query)
    
    # формирование списков значений с данными и временем
    time_index = data[3].index('_time')
    meas_index = data[3].index('_value')
    time = list()
    meas = list()
    for i in range(len(data[4:-1])):
        time.append(data[4+i][time_index])
        meas.append(data[4+i][meas_index])
    
    return JsonResponse(data={
        'time': time,
        'meas': meas,
    })




#class IndexView(generic.ListView):
#    template_name = 'sensorslist/sensors.html'
#    context_object_name = 'all_sensors'#
#
#    def get_queryset(self):
#        return Question.objects.all()

login/templates/login/login.html
{% block content %}      

<!--Login--> 
<div class="container py-5">
  <h1>Авторизация</h1>
  <form method="POST">
    {% csrf_token %}    
    <table>
        <tbody>
            {% for form in login_form %}
            <tr>
                <p><td><label class="form-label" for="{{ form.id_label }}">{{form.label}}: </label></td><td>{{ form }}</td></p>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-primary" type="submit">Войти</button>
  </form>
  <p class="text-center">Нет аккаунта? <a href="{% url 'registration:registration' %}">Создать аккаунт</a>.</p>
</div>

{% endblock %}

sensorslist/templates/sensorslist/sensors.html
<!DOCTYPE html>
<html>
    
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/sensorslist/">SensorsApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            
            <li class="nav-item">
            <a class="nav-link" href="{% url 'login:login' %}">Logout</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Welcome, {{user.username}}</a>
            </li>

            {% else %}

            <li class="nav-item">
            <a class="nav-link" href="{% url 'login:login' %}">Login</a>
            </li>

            {% endif %}
        </ul>
        </div>
    </nav>

    <head>
        <title>Sensors list</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script scr="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <style>
            #container {
                margin: 0px auto;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div id="container" class="container-fluid">
            <h3>Sensors list</h3>
            <button onclick="addNewRow()" class="btn btn-primary">Add new sensor</button>
            <br>
            <br>
            <table id="sensors-table" class="table table-bordered table-striped">
                <tr>
                    <th>User name</th>
                    <th>Sensor name</th>
                    <th>Action</th>
                </tr>

                {% for sensor in sensors_list %}
                <tr>
                    <td id="user">{{ sensor.user }}</td>
                    <td id="sensor">{{ sensor.name }}</td>
                    <td>
                        <input class="btn btn-primary" type="button" value="Load new data" onclick="loadNewData(this)" />
                        <input class="btn btn-info" type="button" value="Plot data" onclick="plotData(this)" />
                        <input class="btn btn-danger" type="button" value="Delete" onclick="deleteRow(this)" />
                    </td>
                </tr>
                <tr>
                    <div id="container" style="width: 40%;">
                        <canvas id="plot_data" data-url="{% url 'sensorslist:plot_data' %}"></canvas>
                    </div>
                </tr>
                {% endfor %}
            </table>
        </div>
    </body>

    <script src="https://yastatic.net/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script type="text/javascript">

        function addNewRow() {
            var table = document.getElementById("sensors-table");
            var rowCount = table.rows.length;
            var cellCount = table.rows[0].cells.length;
            var row = table.insertRow(rowCount);

            row.insertCell(0).innerHTML = '{{ username }}';
            row.insertCell(1).innerHTML = '<input type="text" class="form-control" value="" />';
            row.insertCell(2).innerHTML = '<input class="btn btn-danger" '
                    + ' type="button" value="Delete" onclick="deleteRow(this)" />'
                    + ' <input class="btn btn-success" type="button" value="Save" onclick="saveNewData(this)" />';
        }

        function deleteRow(ele) {
            var table = document.getElementById("sensors-table");
            var rowCount = table.rows.length;
            var row = ele.parentNode.parentNode;
            console.log('rowIndex = ', row.rowIndex);

            if (ele) {
                // delete specifc row
                var tr = document.querySelectorAll('tr');
                var needtr = tr[row.rowIndex].querySelectorAll('td');
                var objectData =
                {
                    User: needtr[0].innerHTML,
                    Name: needtr[1].innerHTML
                };
                console.log('object: ', objectData);

                $.ajax({
                    type: "POST",
                    url: "http://127.0.0.1:8000/sensorslist/delete_data/", //add new url for each of the activity,
                    dataType: "json",
                    data: objectData,
                });
                row.parentNode.removeChild(row);
            }
        }

        function saveNewData(ele) {
            var table = document.getElementById('sensors-table');
            var row = ele.parentNode.parentNode;

            if (ele) {
                var tr = document.querySelectorAll('tr');
                var row_index = row.rowIndex
                var user_name = tr[row_index].querySelectorAll('td')[0].innerHTML;
                var sensor_name = tr[row_index].querySelectorAll('input')[0].value;
                var objectData =
                {
                    User: user_name,
                    Name: sensor_name // name of sensor!
                };
                
                $.ajax({
                    type: "POST",
                    url: "http://127.0.0.1:8000/sensorslist/save_data/", //add new url for each of the activity,
                    dataType: "json",
                    data: objectData,
                });

                console.log('object: ', objectData);
                
                /*
                удаление строки для ввода данных
                отображение новых данных в виде текста
                */
                row.parentNode.removeChild(row);

                var newrow = table.insertRow(row_index);
                var newcellCount = table.rows[0].cells.length;

                for (var i = 0; i < newcellCount; i++) {
                    var newcell = newrow.insertCell(i);
                    if (i < newcellCount-1) {
                        newcell.innerHTML = '<td>' + Object.values(objectData)[i] + '</td>';
                    }
                    else {
                        newcell.innerHTML = '<td> '
                            + '<input class="btn btn-primary" type="button" value="Load new data" onclick="loadNewData(this)" />'
                            + ' <input class="btn btn-info" type="button" value="Plot data" onclick="plotData(this)" />'
                            + ' <input class="btn btn-danger" type="button" value="Delete" onclick="deleteRow(this)" />'
                        + '</td>';
                    }
                }
            }
        }

        function loadNewData(ele) {
            var table = document.getElementById('sensors-table');
            var row = ele.parentNode.parentNode;

            if (ele) {
                var tr = document.querySelectorAll('tr');
                var row_index = row.rowIndex
                var sensor_name = tr[row_index].querySelectorAll('td')[1].innerHTML;
                var objectData =
                {
                    Name: sensor_name // name of sensor!
                };
                console.log('object: ', objectData);
                $.ajax({
                    type: "POST",
                    url: "http://127.0.0.1:8000/sensorslist/load_data/", //add new url for each of the activity,
                    dataType: "json",
                    data: objectData,
                });
            }
        }

        
            

        // добавить этот элемент в html-разметку в новую строку!
        
        
        function plotData(ele) {
            var table = document.getElementById('sensors-table');
            var row = ele.parentNode.parentNode;

            if (ele) {
                var tr = document.querySelectorAll('tr');
                var row_index = row.rowIndex
                var sensor_name = tr[row_index].querySelectorAll('td')[1].innerHTML;
                var objectData =
                {
                    Name: sensor_name // name of sensor!
                };
                console.log('object: ', objectData);

                var $measurementChart = $("#plot_data");
                $.ajax({
                    type: "POST",
                    url: "http://127.0.0.1:8000/sensorslist/plot_data/", //add new url for each of the activity,
                    dataType: "json",
                    data: objectData,
                    success :function (data) {

                        var ctx = $measurementChart[0].getContext("2d");

                        new Chart(ctx, {
                            type: 'line',
                            data: {
                                labels: data.time,
                                datasets: [{
                                    label: 'Temperature',
                                    backgroundColor: 'blue',
                                    data: data.meas,
                                    fill: false,
                                }]
                            },
                            options: {
                                responsive: true,
                                legend: {
                                    position: 'top',
                                },
                                title: {
                                    display: true,
                                    text: 'Temperature values'
                                },
                                scales: {
                                    xAxes: [{
                                        display: true,
                                        scaleLabel: {
                                            display: true,
                                            labelString: 'Date'
                                        }
                                    }],
                                    yAxes: [{
                                        display: true,
                                        scaleLabel: {
                                            display: true,
                                            labelString: 'Temperature'
                                        }
                                    }]
                                }
                            }
                        });
                    }
                });
            }

            // график
            // var $measurementChart = $("#plot_data");
            // $.ajax({
            //     url: $measurementChart.data("url"),
            //     success: function (data) {

            //     var ctx = $measurementChart[0];//.getContext("2d");

            //     new Chart(ctx, {
            //         type: 'bar',
            //         data: {
            //             labels: data.time,
            //             datasets: [{
            //                 label: 'Population',
            //                 backgroundColor: 'blue',
            //                 data: data.meas
            //             }]
            //         },
            //         options: {
            //             responsive: true,
            //             legend: {
            //                 position: 'top',
            //         },
            //         title: {
            //             display: true,
            //             text: 'Population Bar Chart'
            //         }
            //         }
            //     });

            //     }
            // });
        }

    </script>
</html>